# ANN 

#### import libraries 

In [1]:

import pandas as pd 
import numpy as np 



In [11]:
np.complex_ = np.complex128
np.float_ = np.float64
#np.string_ = np.bytes_
np.unicode_ = np.str_

In [12]:
np.string_ = np.bytes_

In [3]:
import tensorflow as tf
tf.__version__

'2.12.0'

### Get data 

In [5]:
bank_churn_df = pd.read_csv('../datasets/Deep Learning A-Z/Part 1 - Artificial Neural Networks (ANN)/Churn_Modelling.csv')

In [6]:
bank_churn_df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [73]:
X = bank_churn_df.iloc[:, 3:-1].values ## REMOVING ID, NAME , customer name 
y = bank_churn_df.iloc[:, -1].values

In [74]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

### Encoding

In [75]:
## Converting gender column to 0,1 
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [76]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [77]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set


In [92]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [93]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN
### Initial Models 


In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


### Adding the second hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))


### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [19]:
ann

## Part 3 - Training the ANN
### Compiling the ANN

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [21]:
ann.fit(X_train,y_train,batch_size = 32,epochs=100)

Epoch 1/100
250/250 [==============================] - 2s 2ms/step - loss: 0.5912 - accuracy: 0.7081
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4765 - accuracy: 0.8073
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4452 - accuracy: 0.8134
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4314 - accuracy: 0.8156
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4229 - accuracy: 0.8189
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4166 - accuracy: 0.8202
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4119 - accuracy: 0.8229
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4066 - accuracy: 0.8244
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3997 - accuracy: 0.8271
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3901 - accura

In [22]:
ann.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (32, 6)                   78        
                                                                 
 dense_1 (Dense)             (32, 6)                   42        
                                                                 
 dense_2 (Dense)             (32, 1)                   7         
                                                                 
Total params: 127
Trainable params: 127
Non-trainable params: 0
_________________________________________________________________


In [24]:
bank_churn_df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [110]:
homework_df = pd.DataFrame(np.array([[600,'France','Male',40,3, 60000,2,1, 1,50000]]),columns=['CreditScore', 'Geography','Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard','IsActiveMember', 'EstimatedSalary'])

In [111]:
homework_df

CreditScore Geography Gender Age Tenure Balance NumOfProducts HasCrCard  \
0         600    France   Male  40      3   60000             2         1   

  IsActiveMember EstimatedSalary  
0              1           50000

In [112]:
homework_value = homework_df.values

In [113]:
homework_value

array([['600', 'France', 'Male', '40', '3', '60000', '2', '1', '1',
        '50000']], dtype=object)

In [114]:
homework_value[:, 2] = le.transform(homework_value[:, 2])

In [115]:
homework_X = np.array(ct.transform(homework_value))

In [116]:
homework_X_sc = sc.transform(homework_X)

In [117]:
homework_X.T

array([[1.0],
       [0.0],
       [0.0],
       ['600'],
       [1],
       ['40'],
       ['3'],
       ['60000'],
       ['2'],
       ['1'],
       ['1'],
       ['50000']], dtype=object)

In [119]:
ann.predict(homework_X_sc)

1/1 [==============================] - 0s 47ms/step


array([[0.02315692]], dtype=float32)

In [120]:
ann.predict(homework_X_sc) > 0.5

1/1 [==============================] - 0s 34ms/step


array([[False]])

### predicting 

In [121]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 961us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [122]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   83]
 [ 195  210]]


0.861